language: cpp
sudo: false
compiler:
  - clang
  - gcc
addons:
  apt:
    sources:
      - kubuntu-backports
    packages:
      - cmake
      - cmake-data
      - libboost-dev
      - libcppunit-dev
      - libboost-test-dev
      - libgtest-dev
before_script:
  - "cmake --version"
  - "mkdir gtest-bin && cd gtest-bin && cmake /usr/src/gtest && make && cd .."
script:
  - export CMAKE_LIBRARY_PATH=$(pwd)/gtest-bin
  - "mkdir build && cd build && cmake .. && make && ctest -V"
